{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "from azureml.core import Workspace, Experiment\n",
    "\n",
    "# Configure experiment\n",
    "ws = Workspace.from_config()\n",
    "exp = Experiment(workspace=ws, name='cifar10_cnn_as_mount')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "from azureml.core import Dataset\n",
    "\n",
    "ds = Dataset.get_by_name(ws, name='cifar10')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from azureml.core.compute import ComputeTarget, AmlCompute\n",
    "from azureml.core.compute_target import ComputeTargetException\n",
    "\n",
    "# cluster configuration\n",
    "cluster_name = \"mldemocompute\"\n",
    "min_nodes = 0\n",
    "max_nodes = 2\n",
    "vm_size = \"STANDARD_D2_V2\"\n",
    "\n",
    "# verify that the cluster exists already\n",
    "try:\n",
    "    aml_cluster = ComputeTarget(workspace=ws, name=cluster_name)\n",
    "except ComputeTargetException:\n",
    "    print('Cluster not `%s` not found, creating one now.' % cluster_name)\n",
    "    config = AmlCompute.provisioning_configuration(vm_size=vm_size, min_nodes=min_nodes, max_nodes=max_nodes)\n",
    "    aml_cluster = ComputeTarget.create(workspace=ws, name=cluster_name, provisioning_configuration=config)\n",
    "\n",
    "# wait until the cluster is ready\n",
    "aml_cluster.wait_for_completion(show_output=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from azureml.core import Environment\n",
    "\n",
    "# define the PIP requirements file location\n",
    "pipreq = 'requirements.txt'\n",
    "pipreq_path = os.path.join(os.getcwd(), '.azureml', pipreq)\n",
    "\n",
    "# set a remote environment from a PIP requirement file\n",
    "myenv = Environment.from_pip_requirements(name = \"remote_env\", file_path = pipreq_path)\n",
    "# show environment object\n",
    "myenv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "d427a7012b084265941e0796a9875cd1",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "_UserRunWidget(widget_settings={'childWidgetDisplay': 'popup', 'send_telemetry': False, 'log_level': 'INFO', 'â€¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/aml.mini.widget.v1": "{\"status\": \"Failed\", \"workbench_run_details_uri\": \"https://ml.azure.com/runs/cifar10_cnn_as_mount_1630262976_25295906?wsid=/subscriptions/21dc412b-d9eb-42e7-8317-55bc8eb10cf5/resourcegroups/packt/workspaces/mldemows&tid=e702ab66-1ac1-42ba-b41b-8195d943a1e0\", \"run_id\": \"cifar10_cnn_as_mount_1630262976_25295906\", \"run_properties\": {\"run_id\": \"cifar10_cnn_as_mount_1630262976_25295906\", \"created_utc\": \"2021-08-29T18:49:36.947356Z\", \"properties\": {\"_azureml.ComputeTargetType\": \"local\", \"ContentSnapshotId\": \"44c97c30-bcf7-453d-94f4-5e15aae782d9\"}, \"tags\": {}, \"script_name\": null, \"arguments\": null, \"end_time_utc\": \"2021-08-29T18:50:44.057498Z\", \"status\": \"Failed\", \"log_files\": {\"azureml-logs/60_control_log.txt\": \"https://mldemows8396108817.blob.core.windows.net/azureml/ExperimentRun/dcid.cifar10_cnn_as_mount_1630262976_25295906/azureml-logs/60_control_log.txt?sv=2019-07-07&sr=b&sig=66bTRZV3mOWFD9ePjcSw9cz3XpIG9VeDZQECWfCNCN8%3D&st=2021-08-29T18%3A40%3A46Z&se=2021-08-30T02%3A50%3A46Z&sp=r\", \"azureml-logs/70_driver_log.txt\": \"https://mldemows8396108817.blob.core.windows.net/azureml/ExperimentRun/dcid.cifar10_cnn_as_mount_1630262976_25295906/azureml-logs/70_driver_log.txt?sv=2019-07-07&sr=b&sig=BFcrcM4pUvZwWGdhLZi7TekaWDGePuYBul5FFr8ERQQ%3D&st=2021-08-29T18%3A40%3A46Z&se=2021-08-30T02%3A50%3A46Z&sp=r\"}, \"log_groups\": [[\"azureml-logs/60_control_log.txt\"], [\"azureml-logs/70_driver_log.txt\"]], \"run_duration\": \"0:01:07\", \"run_number\": \"4\", \"run_queued_details\": {\"status\": \"Failed\", \"details\": null}}, \"child_runs\": [], \"children_metrics\": {}, \"run_metrics\": [], \"run_logs\": \"[2021-08-29T18:49:38.508275] Entering context manager injector.\\n[2021-08-29T18:49:39.176676] context_manager_injector.py Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'Dataset:context_managers.Datasets', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError'], invocation=['cifar10_cnn_remote.py', '--input', 'DatasetConsumptionConfig:cifar10'])\\n[2021-08-29T18:49:39.246] Initialize DatasetContextManager.\\nScript type = None\\n[2021-08-29T18:49:39.400624] Logging warning in history service: ERROR:: Dataset  failed. . Exception Details:Traceback (most recent call last):\\n  File \\\"/private/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/azureml_runs/cifar10_cnn_as_mount_1630262976_25295906/azureml-setup/context_managers.py\\\", line 488, in __enter__\\n    self._generate_path_on_compute()\\n  File \\\"/private/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/azureml_runs/cifar10_cnn_as_mount_1630262976_25295906/azureml-setup/context_managers.py\\\", line 622, in _generate_path_on_compute\\n    prepare_input(key, value)\\n  File \\\"/private/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/azureml_runs/cifar10_cnn_as_mount_1630262976_25295906/azureml-setup/context_managers.py\\\", line 592, in prepare_input\\n    path_on_compute, user_path_on_compute = do_generate_path_on_compute(\\n  File \\\"/private/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/azureml_runs/cifar10_cnn_as_mount_1630262976_25295906/azureml-setup/context_managers.py\\\", line 551, in do_generate_path_on_compute\\n    os.chmod(path_on_compute, mode=0o777)\\nOSError: [Errno 30] Read-only file system: '/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/cifar10_0217c2d7-057e-486a-a133-5b0e0f15716a'\\n\\nStarting the daemon thread to refresh tokens in background for process with pid = 17314\\n[2021-08-29T18:49:39.659861]Hosttool Job Error file path is not set\\nTraceback (most recent call last):\\n  File \\\"azureml-setup/context_manager_injector.py\\\", line 455, in <module>\\n    execute_with_context(cm_objects, options.invocation)\\n  File \\\"azureml-setup/context_manager_injector.py\\\", line 132, in execute_with_context\\n    stack.enter_context(wrapper)\\n  File \\\"/private/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/azureml_runs/cifar10_cnn_as_mount_1630262976_25295906/azureml-setup/_vendor_contextlib2.py\\\", line 356, in enter_context\\n    result = _cm_type.__enter__(cm)\\n  File \\\"azureml-setup/context_manager_injector.py\\\", line 80, in __enter__\\n    self.context_manager.__enter__()\\n  File \\\"/private/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/azureml_runs/cifar10_cnn_as_mount_1630262976_25295906/azureml-setup/context_managers.py\\\", line 488, in __enter__\\n    self._generate_path_on_compute()\\n  File \\\"/private/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/azureml_runs/cifar10_cnn_as_mount_1630262976_25295906/azureml-setup/context_managers.py\\\", line 622, in _generate_path_on_compute\\n    prepare_input(key, value)\\n  File \\\"/private/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/azureml_runs/cifar10_cnn_as_mount_1630262976_25295906/azureml-setup/context_managers.py\\\", line 592, in prepare_input\\n    path_on_compute, user_path_on_compute = do_generate_path_on_compute(\\n  File \\\"/private/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/azureml_runs/cifar10_cnn_as_mount_1630262976_25295906/azureml-setup/context_managers.py\\\", line 551, in do_generate_path_on_compute\\n    os.chmod(path_on_compute, mode=0o777)\\nOSError: [Errno 30] Read-only file system: '/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/cifar10_0217c2d7-057e-486a-a133-5b0e0f15716a'\\n\\n[2021-08-29T18:49:39.865361] Finished context manager injector with Exception.\\n\\nError occurred: Dataset initialization failed: [Errno 30] Read-only file system: '/var/folders/dq/w2q25sxj32l_4y56t759w42r0000gn/T/cifar10_0217c2d7-057e-486a-a133-5b0e0f15716a'\\n\", \"graph\": {}, \"widget_settings\": {\"childWidgetDisplay\": \"popup\", \"send_telemetry\": false, \"log_level\": \"INFO\", \"sdk_version\": \"1.33.0\"}, \"loading\": false}"
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from azureml.widgets import RunDetails\n",
    "from azureml.core import ScriptRunConfig\n",
    "\n",
    "src = ScriptRunConfig(source_directory=\"code\",\n",
    "                      script='cifar10_cnn_remote.py',\n",
    "                      arguments=['--input', ds.as_named_input('cifar10').as_mount()],\n",
    "                      ompute_target = aml_cluster,\n",
    "                      environment = myenv)\n",
    "\n",
    "run = exp.submit(src)\n",
    "RunDetails(run).show()"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "c39ce73b6d48f343ffd00681afb9b3f63104480cfaffe0ebb445fe41a6801158"
  },
  "kernelspec": {
   "display_name": "Python 3.8.2 64-bit ('packt-repo-M2qY5kM-': pipenv)",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
